# Generated by Django 5.2.5 on 2026-06-15 11:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0003_questionbank_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionbank",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="questionbank",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
