# Generated by Django 5.2.5 on 2026-06-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0004_questionbank_created_at_questionbank_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionbank",
            name="tags",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
