# Generated by Django 5.2.5 on 2026-06-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0005_questionbank_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="options",
            field=models.JSONField(default=list),
        ),
    ]
