# Generated by Django 5.2.5 on 2026-06-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0006_question_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionbank",
            name="export_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
