# Generated by Django 5.2.5 on 2026-06-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0007_questionbank_export_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("generate", "Generated Questions"),
                            ("bank", "Created Question Bank"),
                            ("export", "Exported"),
                            ("delete", "Deleted Question Bank"),
                            ("edit", "Edited Question Bank"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("subject", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
